version: '3.8'

services:

  jersey-microservice-management:
    build:
      context: ./jersey-microservice-management
    image: jersey-microservice-management-img
    container_name: jersey-microservice-management-api
    ports:
      - "8084:8080"
    networks:
      - mysqlnetwork

  jersey-microservice-transactions:
    build:
      context: ./jersey-microservice-transactions
    image: jersey-microservice-transactions-img
    container_name: jersey-microservice-transactions-api
    ports:
      - "8085:8080"
    networks:
      - mysqlnetwork

  jersey-microservice-billing:
    build:
      context: ./jersey-microservice-billing
    image: jersey-microservice-billing-img
    container_name: jersey-microservice-billing-api
    ports:
      - "8086:8080"
    networks:
      - mysqlnetwork

  jersey-microservice-dispute:
    build:
      context: ./jersey-microservice-dispute
    image: jersey-microservice-dispute-img
    container_name: jersey-microservice-dispute-api
    ports:
      - "8087:8080"
    networks:
      - mysqlnetwork

networks:
  mysqlnetwork:
    external: true  # 使用外部已存在的網路