version: '3.8'

services:
#  jdbc-billofmonth-api:
#    image: jdbc-billofmonth-api-img
#    container_name: jdbc-billofmonth-api
#    ports:
#      - "8082:8080"
#    networks:
#      - mysqlnetwork
#
#  jdbc-billrecord-api:
#    image: jdbc-billrecord-api-img
#    container_name: jdbc-billrecord-api
#    ports:
#      - "8083:8080"
#    networks:
#      - mysqlnetwork
#
#  jdbc-cuscredit-api:
#    image: jdbc-cuscredit-api-img
#    container_name: jdbc-cuscredit-api
#    ports:
#      - "8081:8080"
#    networks:
#      - mysqlnetwork

  jersey-microservice-management:
    build:
      context: ./jersey-microservice-management
    image: jersey-microservice-management-img
    container_name: jersey-microservice-management-api
    ports:
      - "8084:8080"
#    depends_on:
#      - jdbc-billofmonth-api
#      - jdbc-billrecord-api
#      - jdbc-cuscredit-api
    networks:
      - mysqlnetwork

  jersey-microservice-transactions:
    build:
      context: ./jersey-microservice-transactions
    image: jersey-microservice-transactions-img
    container_name: jersey-microservice-transactions-api
    ports:
      - "8085:8080"
#    depends_on:
#      - jdbc-billofmonth-api
#      - jdbc-billrecord-api
#      - jdbc-cuscredit-api
    networks:
      - mysqlnetwork

  jersey-microservice-billing:
    build:
      context: ./jersey-microservice-billing
    image: jersey-microservice-billing-img
    container_name: jersey-microservice-billing-api
    ports:
      - "8086:8080"
#    depends_on:
#      - jdbc-billofmonth-api
#      - jdbc-billrecord-api
#      - jdbc-cuscredit-api
    networks:
      - mysqlnetwork

  jersey-microservice-dispute:
    build:
      context: ./jersey-microservice-dispute
    image: jersey-microservice-dispute-img
    container_name: jersey-microservice-dispute-api
    ports:
      - "8087:8080"
#    depends_on:
#      - jdbc-billofmonth-api
#      - jdbc-billrecord-api
#      - jdbc-cuscredit-api
    networks:
      - mysqlnetwork

networks:
  mysqlnetwork:
    external: true  # 使用外部已存在的網路